### PR TITLE
Bug 682: maven/tests javax.media.opengl.* -> com.jogamp.opengl.*

### PR DESCRIPTION
**Pull request by xranby**

### CODE REVIEW

**Comment by ghost** [comment]
Oops, we forgot those files. Good job :)

**Comment by io7m** [comment]
Why didn't this one get merged?

**Comment by ghost** [comment]
@io7m Done :)

**Comment by io7m** [comment]
Thanks.

Is this the canonical repos for this stuff now?

If not... How do changes added here make it back into whatever is the canonical repos?

**Comment by xranby** [comment]
Changes added here make it back to the canonical repository’s by having one of the JogAmp team logging into the jogamp.org server by ssh using it's personal key and do a git pull

**Comment by io7m** [comment]
Hm, right.

**Pull request merged**
